export type ThemePresetId = "codexDark" | "graphite" | "highContrast";

export const themePresets = {
  codexDark: {
    id: "codexDark",
    name: "Codex Dark",
    description: "Matches the current Codex blue control palette.",
    background: "#0b1220",
    backgroundElevated: "#111a2b",
    backgroundMuted: "#162133",
    card: "#0f1728",
    cardSoft: "#172235",
    cardAccent: "#1d2b43",
    border: "#2a3a56",
    text: "#f4f7fb",
    textMuted: "#a8b4c8",
    textSubtle: "#7f90ab",
    primary: "#5cb3ff",
    primaryStrong: "#2c86d1",
    onAccent: "#ffffff",
    success: "#1d8f63",
    danger: "#c2556b",
    warning: "#d4a340",
    noticeErrorBackground: "#341924",
    noticeErrorBorder: "#5f2a3a",
    noticeErrorText: "#ffb7c4",
    noticeSuccessBackground: "#102a23",
    noticeSuccessBorder: "#1f5b48",
    noticeSuccessText: "#8fe0bf",
    userBubbleText: "#ffffff",
    userBubbleMeta: "#bbcee6",
    userBubbleRole: "#d8efff",
    shadow: "#000000",
  },
  graphite: {
    id: "graphite",
    name: "Graphite",
    description: "Lower-saturation surfaces for longer reading sessions.",
    background: "#0d1117",
    backgroundElevated: "#151b23",
    backgroundMuted: "#1b232e",
    card: "#111820",
    cardSoft: "#19222d",
    cardAccent: "#222d3a",
    border: "#354251",
    text: "#f2f5f8",
    textMuted: "#b2bdc9",
    textSubtle: "#8996a6",
    primary: "#8ab4f8",
    primaryStrong: "#3f7fbf",
    onAccent: "#ffffff",
    success: "#3aa675",
    danger: "#d36a7d",
    warning: "#d1a957",
    noticeErrorBackground: "#2f1d24",
    noticeErrorBorder: "#6a3443",
    noticeErrorText: "#ffc2cf",
    noticeSuccessBackground: "#132922",
    noticeSuccessBorder: "#2a684f",
    noticeSuccessText: "#a2e8ca",
    userBubbleText: "#ffffff",
    userBubbleMeta: "#d2dcea",
    userBubbleRole: "#eff6ff",
    shadow: "#000000",
  },
  highContrast: {
    id: "highContrast",
    name: "High Contrast",
    description: "Stronger text and borders for glare and accessibility.",
    background: "#020617",
    backgroundElevated: "#07101f",
    backgroundMuted: "#0d1b2f",
    card: "#08111f",
    cardSoft: "#0f1d33",
    cardAccent: "#17355d",
    border: "#6682a8",
    text: "#ffffff",
    textMuted: "#dce7f8",
    textSubtle: "#b7c8e2",
    primary: "#93c5fd",
    primaryStrong: "#2563eb",
    onAccent: "#ffffff",
    success: "#22c55e",
    danger: "#fb7185",
    warning: "#facc15",
    noticeErrorBackground: "#4a1624",
    noticeErrorBorder: "#fb7185",
    noticeErrorText: "#ffe4ea",
    noticeSuccessBackground: "#06351f",
    noticeSuccessBorder: "#22c55e",
    noticeSuccessText: "#dcfce7",
    userBubbleText: "#ffffff",
    userBubbleMeta: "#e0edff",
    userBubbleRole: "#f8fbff",
    shadow: "#000000",
  },
} as const;

export type ThemeColors = (typeof themePresets)[ThemePresetId];

export const DEFAULT_THEME_PRESET_ID: ThemePresetId = "codexDark";
export const colors = themePresets[DEFAULT_THEME_PRESET_ID];

export function normalizeThemePresetId(value: unknown): ThemePresetId {
  return typeof value === "string" && value in themePresets
    ? (value as ThemePresetId)
    : DEFAULT_THEME_PRESET_ID;
}
